version: '3'
services:
  db:
    image: postgres:13-alpine
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lumberghini
      - POSTGRES_PASSWORD=lumberghini
      - POSTGRES_DB=lumberghini
