camunda.bpm:
  history-level: FULL
  default-serialization-format: application/json
  webapp:
    index-redirect-enabled: false
    application-path: "/"
  id-generator: strong
  admin-user:
    id: admin
  filter:
    create: All
  metrics:
    enabled: false
    db-reporter-activate: false
  generic-properties:
    properties:
      initializeTelemetry: false
      telemetryReporterActivate: false
