spring:
  datasource:
    url: "jdbc:h2:mem:${spring.application.name};DB_CLOSE_DELAY=-1"
    driverClassName: org.h2.Driver
    username: "sa"
    password: "sa"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: true
