# https://www.rottentomatoes.com/m/office_space/quotes/
lumberghini.tasks:
  - name: "Please give me my stapler"
    description: "I need my stapler."
    colleague: Milton

  - name: "Hello {firstName} what's happening."
    description: "I'm gonna need you to go ahead and come in tomorrow. So if you could be here at around....9 that'd be great."
    colleague: Bill

  - name: "I believe you have my stapler."
    description: "I need my stapler"
    colleague: Milton

  - name: "Did you get my memo?"
    description: "Well, Did you?"
    colleague: Bill

  - name: "Oh, and remember: next Friday... is Hawaiian shirt day."
    description: "So, you know, if you want to, go ahead and wear a Hawaiian shirt and jeans."
    colleague: Bill

  - name: "Listen, are you gonna have those TPS reports for us this afternoon?"
    description: "Hello {firstName}, what's happening? Listen, are you gonna have those TPS reports for us this afternoon?"
    colleague: Bill

  - name: "Ah. Well then I suppose we should go ahead and have a little talk."
    description: "Ah. Well then I suppose we should go ahead and have a little talk."
    colleague: Bill

  - name: "Excuse me, but I think you have my stapler."
    description: "-"
    colleague: Milton

  - name: "I'm also gonna need you to go ahead and come in on Sunday."
    description: "Yeah........ I'm gonna need you to come in on Saturday."
    colleague: Bill

  - name: "I’m going to need those TPS reports."
    description: "I’m going to need those TPS reports...ASAP...So, if you could do that, that’d be great...."
    colleague: Bill

  - name: "We need to talk about your TPS reports."
    description: "What's happening"
    colleague: Dom

  - name: "We use a different cover sheet now for the TPS reports.."
    description: "Yeah. The coversheet. I know, I know. Uh, Bill talked to me about it."
    colleague: Dom

  - name: "Yeah. Uh, did you get that memo?"
    description: "Yeah. It's just that we're putting new coversheets on all the TPS reports *before* they go out now. So if you could just remember to do that from now on, that'd be great. All right!"
    colleague: Dom

  - name: "You were supposed to come in Saturday."
    description: "You were supposed to come in Saturday. What were you doing"
    colleague: Michael

  - name: "I'm going to need those TPS reports."
    description: "As soon as possible"
    colleague: Bill

  - name: "So, if you could do that"
    description: "that would be great..."
    colleague: Bill

  - name: "I'm also going to need you to go ahead and come in on Sunday, too."
    description: "We, uhhh, lost some people this week and we sorta need to play catch-up. Mmmmmkay? Thaaaaaanks."
    colleague: Bill

  - name: "We're gonna need to go ahead and move you downstairs into storage B."
    description: "We have some new people coming in, and we need all the space we can get. So if you could go ahead and pack up your stuff and move it down there, that would be terrific, mmmK?"
    colleague: Bill
