application:
  name: lumberghini
  port: 8081
  lumberghini:
    quotes: "hello World"
#      list:
#        - "Ummh, actually ..."

spring:
  application:
    name: ${application.name}
  datasource:
    url: jdbc:postgresql://localhost/${application.name}
    username: ${application.name}
    password: ${application.name}
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    open-in-view: true

server:
  port: ${application.port}

camunda:
  bpm:
    admin-user:
      id: admin
    filter:
      create: All

lumberghini:
  quotes:
    list:
      - "Ummh, actually ..."

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
