spring:
  application:
    name: lumberghini
  config:
    import:
      - classpath:config/datasource.yml
      - classpath:config/tasks.yml
      - classpath:config/camunda.yml

server:
  port: ${PORT:8081}
