application:
  name: lumberghini
  port: 8081
  lumberghini:
    quotes: "hello World"
#      list:
#        - "Ummh, actually ..."

spring:
  application:
    name: ${application.name}
  datasource:
    url: "jdbc:h2:mem:${application.name}"
    driverClassName: org.h2.Driver
    username: "sa"
    password: "sa"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate.ddl-auto: none
    show-sql: false
    open-in-view: true

server:
  port: ${application.port}

camunda:
  bpm:
    admin-user:
      id: admin
    filter:
      create: All

lumberghini:
  quotes:
    list:
      - "Ummh, actually ..."
