spring:
  application:
    name: lumberghini
  config:
    import:
      - classpath:config/datasource.yml
      - classpath:config/tasks.yml
      - classpath:config/camunda.yml
  jersey:
    # set Camunda's rest path to /rest (i.e. cement the default, a reference of which is hardcoded in SecurityConfiguration)
    application-path: "/rest"
  groovy:
    template:
      check-template-location: false # disable groovy template warning

server:
  port: ${PORT:8081}
  max-http-header-size: 16KB

#logging:
#  level:
#    # To log REST controllers
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
#    # To log web access
#    org.springframework.web: TRACE
#    org:
#      springframework:
#        web:
#          servlet:
